builders:
  - script
triggers:
  cron: "@weekly"
clean_workspace: true

script:
  - "echo no tests yet"
#
#extra_jobs:
#  - name: sunet-stats-processor-docker
#    builders:
#      - docker
#    docker_name: stats-processor
#    managed_scripts:
#      - docker_build_prep.sh
#      - docker_tag.sh
#    triggers:
#      github_push: false
#      cron: null
#    upstream:
#      - sunet-stats-processor
